import '@/app/global.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Wheel',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	)
}
